CREATE DATABASE CadastroClientes;

USE CadastroClientes;

CREATE TABLE Moedas (
    MOEDA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MOEDA_CODIGO SMALLINT not NULL UNIQUE,
    MOEDA_SIGLA VARCHAR(150) NOT NULL,
    MOEDA_QDEC SMALLINT NOT NULL
);

CREATE TABLE Clientes (
    CLI_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLI_CODIGO VARCHAR(50) UNIQUE NOT NULL,
    CLI_RZSOC VARCHAR(150) NOT NULL,
    CLI_MOEDA SMALLINT NOT NULL,
    CLI_DTCRE DATE NOT NULL,
    CLI_DTULTVDA DATE,
    CLI_VRVDA DECIMAL(10, 4) NOT NULL,
    FOREIGN KEY(CLI_MOEDA) REFERENCES Moedas(MOEDA_CODIGO)
);
