USE CadastroClientes;

INSERT INTO moedas (MOEDA_CODIGO, MOEDA_SIGLA, MOEDA_QDEC) VALUES (986, 'BRL', 2);
INSERT INTO moedas (MOEDA_CODIGO, MOEDA_SIGLA, MOEDA_QDEC) VALUES (978, 'EUR', 4);
INSERT INTO moedas (MOEDA_CODIGO, MOEDA_SIGLA, MOEDA_QDEC) VALUES (840, 'USD', 4);
INSERT INTO moedas (MOEDA_CODIGO, MOEDA_SIGLA, MOEDA_QDEC) VALUES (826, 'GBP', 2);
INSERT INTO moedas (MOEDA_CODIGO, MOEDA_SIGLA, MOEDA_QDEC) VALUES (392, 'JPY', 0);
